# Generated by Django 2.2.8 on 2020-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregsystem', '0010_auto_20200305_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=80)),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('comment', models.CharField(max_length=80)),
                ('member', models.CharField(max_length=80)),
                ('approver', models.CharField(max_length=80)),
                ('deleted', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'MobilePay Payments',
            },
        ),
    ]
